### ISSUE TITLE
Colors on NS_ENUM definition

### ISSUE THREAD

**Issue by lancep** [kolinkrewinkel/Polychromatic#16]
NS_ENUM definitions are colored when they shouldn't be.

![screenshot 2014-04-08 13 45 30](https://cloud.githubusercontent.com/assets/1613881/2648346/8559b778-bf56-11e3-8d76-2088ea2c5787.png)

**Comment by kolinkrewinkel** [comment]
The coloring in line 51 is (last I checked) unavoidable, but the coloring on lines 52–54 is intended.
