### ISSUE TITLE
Xcode 6, Swift Rewrite, Swift Support.

### ISSUE THREAD

**Issue by kolinkrewinkel** [kolinkrewinkel/Polychromatic#30]
This'll probably get broken into more than one issue.

I'm going to rewrite this in Swift, as my first experience with it. Probably won't happen for a week or so due to finals and starting work at Facebook.

The rewrite will naturally support Xcode 6, and will likely involve some changes based upon whatever revelations I learn from actually looking at Swift code; from what I can tell, type-inference could be used to affect colors, different coloring priority (like the default themes have now with selectors and types), etc.

Looking forward to it, and any feedback for me going forward.

**Comment by danielgomezrico** [comment]
Still not working for XCode 6.2 beta in swift.

**Comment by freak4pc** [comment]
It never worked for Swift unfortunately... Works fine for Obj-C on Xcode > 6

**Comment by ferologics** [comment]
how's the swift version coming along?

**Comment by kolinkrewinkel** [comment]
It isn't (unless someone else has it working in some capacity); but since I'll be writing Swift on a daily basis now, I may be forced to look into this very shortly.

**Comment by kolinkrewinkel** [comment]
Basically what I'll end up doing in the short term is: Setting a catch-all breakpoint on the layout manager and textview, stepping through it very slowly, and finding out what's being called to provide the temporary color attributes to the text storage-class family.

This combined with a fresh class-dump header set should help. Hopefully it's not too complicated with all the SourceKit XPC stuff.

**Comment by peter-iakovlev** [comment]
If someone is OK with this kind of highlight, you can just use my august 26 commit (9bc84743118f555ffa9d3080c51bb50a2358190e)
![screen shot 2015-02-05 at 18 00 47](https://cloud.githubusercontent.com/assets/6782461/6062467/1bb7a24a-ad61-11e4-8280-df8926487b63.png)

**Comment by freak4pc** [comment]
@peter-iakovlev That's pretty cool but still feels very incomplete ... Especially since everything that doesn't repeat doesn't get the same color ... But it's a great starting point to improve on imo

**Comment by ferologics** [comment]
I did one that looked OK with swift too, check out colorswift on alcatraz if interested... I have it on my github aswellSent using CloudMagicOn št, feb 5, 2015 at 4:05 PM,  kolinkrewinkel/Polychromatic <reply@reply.github.com> wrote:            @peter-iakovlev That's pretty cool but still feels very incomplete ... Especially since everything that doesn't repeat doesn't get the same color ... But it's a great starting point to improve on imo

**Comment by freak4pc** [comment]
@ferologics Saw this one but it's not Polychromatic unfortunately (meaning you don't get unique coloring for different vars, methods, etc...)

**Comment by ferologics** [comment]
Yea, I made it so I would have at least something until the new Polychromatic for swift comes out, didn't think that it would be that long :DSent using CloudMagicOn št, feb 5, 2015 at 4:19 PM,  kolinkrewinkel/Polychromatic <reply@reply.github.com> wrote:            @ferologics Saw this one but it's not Polychromatic unfortunately (meaning you don't get unique coloring for different vars, methods, etc...)

**Comment by kolinkrewinkel** [comment]
@peter-iakovlev Likely what I'm gonna do is pull in your changes to how the color is done first. Big improvement. Then, I'll pull your logic for the Swift highlighting but modify it so it can be flexible and do both.

**Comment by gerald-coddut** [comment]
How about support for XCode 6.2, stopped working there again :(

**Comment by k1vrA** [comment]
@gerald-coddut try put it in ~/Library/Application Support/Developer/Shared/Xcode/Plug-Ins https://yadi.sk/d/W_Fp9g5xbU3QY and restart XCode, It's version for 6.2 ;)

**Comment by gerald-coddut** [comment]
@k1vrA I tried it, but it doesn't work.
Closed XCode, copied the plugin and opened XCode but it did not activate the plugin :o

**Comment by kolinkrewinkel** [comment]
No Swift rewrite. Too much of a pain in the ass with all the hacky categories and swizzling and shit involved. But Xcode 6.2–6.3 and Swift are now supported!
