### ISSUE TITLE
Xcode Version 6.1.1 (6A2008a) can't use Polychromatic.

### ISSUE THREAD

**Issue by jfl913** [kolinkrewinkel/Polychromatic#45]
Xcode Version 6.1.1 (6A2008a) can't use Polychromatic. 
I Install-by-Compilation & Developing, it show
![2015-01-28 1 48 42](https://cloud.githubusercontent.com/assets/1914195/5933041/6720b618-a6f4-11e4-9461-8aaed969b86c.png)

I found Polychromatic.xcplugin was copied into `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ `, but in Xcode->Preferences->Fonts&Colors there is no Polychromatic 
![2015-01-28 1 49 57](https://cloud.githubusercontent.com/assets/1914195/5933053/cd376f64-a6f4-11e4-9632-76ec2891bb0c.png)

**Comment by jfl913** [comment]
I can use it by Polychromatic 1.0.2 – Crash Fixes & Compatibility

**Comment by kolinkrewinkel** [comment]
I assume that the updated release fixed it then – closing.
