### ISSUE TITLE
Xcode 6.2

### ISSUE THREAD

**Issue by poisonedslo** [kolinkrewinkel/Polychromatic#51]
Plugin doesn't work in Xcode 6.2

**Comment by gerald-coddut** [comment]
I second that; the plugin at https://yadi.sk/d/W_Fp9g5xbU3QY does not resolve this either

**Comment by kolinkrewinkel** [comment]
Closed with 8c032b3eb529c25602d8867996b48b81e2e0e20b; final release only.
