### ISSUE TITLE
Cant get them to show up on preferences

### ISSUE THREAD

**Issue by cytryn** [kolinkrewinkel/Polychromatic#52]
For some reason the theme stopped working, I reinstalled the plugin and also alcatraz.

Now I can't even see Polychromatic in the preferences.

**Comment by kolinkrewinkel** [comment]
What version of Xcode and OS X? Also, in the editor menu, can you see the "Polychromatic" submenu?

**Comment by cytryn** [comment]
OS X 10.10.2
Xcode 6.2
What do you mean by "editor menu"? On Alcatraz or Xcode?

**Comment by kolinkrewinkel** [comment]
Within Xcode.

**Comment by skyem** [comment]
It's not in the editor menu for me too. I'm getting this in console logs: [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Polychromatic.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by drozycki** [comment]
I am experiencing the same regression and log as @skyem after updating to XCode 6.2 (6C131e). @kolinkrewinkel lmk what I can do to help fix this issue.

**Comment by drozycki** [comment]
I opened a pull request for the new compatibility strings [here](https://github.com/kolinkrewinkel/Polychromatic/pull/55). I'm running 6.2 and can't install 6.3 so if @skyem or someone else running 6.3 please make sure that my change actually works for them. Also for posterity's sake you can find a discussion of that the compatibility UUID is and why it is necessarily annoying [here](https://github.com/supermarin/Alcatraz/issues/73).

**Comment by skyem** [comment]
I just tried in in 6.3 and it did work. Thanks!
