### ISSUE TITLE
Xcode 6.3 doesn't work.

### ISSUE THREAD

**Issue by jfl913** [kolinkrewinkel/Polychromatic#56]
Xcode 6.3 doesn't work.

**Comment by dezinezync** [comment]
https://github.com/kolinkrewinkel/Polychromatic/commit/2df64911341be646d9f488c5885e05a9bb8da4e1 fixes it.

**Comment by galfaroth** [comment]
It's still not fixed. Doesn't work on official XCode 6.3 release.
