### ISSUE TITLE
Struct members get colored

### ISSUE THREAD

**Issue by mulle-nat** [kolinkrewinkel/Polychromatic#57]
I tried out the plugin, pretty neat. But I was a bit put off by the "gaudy" coloring of code like this

~~~
frame.size.width = 100.0;
~~~
In my experience frame, size, width all get a different color. I think if possible, I would prefer to just have frame colored.
![example](https://cloud.githubusercontent.com/assets/1381995/7106699/9883fd42-e14a-11e4-8702-a7614a0af370.png)

**Comment by kolinkrewinkel** [comment]
Not sure when this got fixed, but it is! :smiley: ![ss 2015-10-27 at 11 40 58](https://cloud.githubusercontent.com/assets/143944/10768699/a1a84ae0-7c9f-11e5-99f5-2cc9f57002ea.png)
