### ISSUE TITLE
Xcode 6.3 doesn't work

### ISSUE THREAD

**Issue by galfaroth** [kolinkrewinkel/Polychromatic#58]
The Polychromatic color scheme doesn't show up on XCode 6.3. And the fix from here doesn't make it work...

**Comment by mhoeller-textunes** [comment]
1) Go to ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/
2) Right-click "Polychromatic.xcplugin" -> Show Package Contents
3) Open Contents/Info.plist in your favourite text editor
4) Add these lines to the DVTPlugInCompatibilityUUIDs section:
<string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
<string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>
5) Save the file and restart Xcode

**Comment by galfaroth** [comment]
I checked that on two macs and in both, the line is apparent but Polychromatic doesn't show up.

Also I might know why it doesn't work. I deleted the whole (~/Library/Application Support/Developer/) folder before updating to XCode 6.3, then after the update I couldn't use Polychromatic (even though I installed it again). Do you think that might have influenced why I can't use Polychromatic?

**Comment by pnutus** [comment]
For me the plug-in made Xcode freeze when a project was opened. Changing the lines suggested by @mhoeller-textunes made it work. I suggest releasing a new version with the fix ASAP.

Also, will the same procedure be necessary for each Xcode update? Seems like a not-great plug-in system…

**Comment by galfaroth** [comment]
Ok found the solution. Type in terminal: 
defaults delete com.apple.dt.Xcode
It will delete all preferences out of your XCode but Polychromatic starts to work immediately.
