### ISSUE TITLE
Variables with different last character get the same color

### ISSUE THREAD

**Issue by cobalamin** [kolinkrewinkel/Polychromatic#62]
![screen shot 2015-06-23 at 08 30 26](https://cloud.githubusercontent.com/assets/669103/8300169/1f004578-1982-11e5-999e-9ac2d91b55fe.png)

The screenshot says it all. Is this behaviour intentional? It makes cases like the last demonstrated one (posX, posY, posZ) very hard to read in comparison. I'd expect those variables specifically to vary strongly in color.

**Comment by micnguyen** [comment]
This is something I've noticed as well. Would love for it to work where it differentiates them.

**Comment by kolinkrewinkel** [comment]
The FNV1a change should resolve this. :smile:
