### ISSUE TITLE
Crashes Xcode 7 Beta when opening Preferences

### ISSUE THREAD

**Issue by cobalamin** [kolinkrewinkel/Polychromatic#65]
The plugin crashes Xcode 7 Beta immediately when I try to open Xcode's Preferences.
Crash report is here: http://pastebin.com/vxhMynNV

Note: I'm aware that it's a Beta version of Xcode, but this might show that there is and will be a different way to handle the Preferences functionality of the plugin in Xcode 7 (?)

**Comment by richardjrossiii** [comment]
Fixed in #67
