### ISSUE TITLE
Settings are resetting after closing Xcode 

### ISSUE THREAD

**Issue by tbaranes** [kolinkrewinkel/Polychromatic#68]
Hi,

Really great tools. Love it
Just a question, each time I restart my mac, and reopen Xcode, my saturation and brightness are back to 0. Why their values are not saved permanently? Did I miss something?

**Comment by kolinkrewinkel** [comment]
In ~/Library/Developer/Xcode/UserData/FontAndColorThemes/, in the color theme you're modifying, at the bottom of the file you should see keys for "PLYVar_______"
What are the values? (Before restart but after quitting Xcode)

**Comment by tbaranes** [comment]
This is the value after restarting, but before launching (I know it's what you asked, but something wrong are in these values):
<key>PLYVarBrightness</key>
<real>0.87937700748443604</real>
<key>PLYVarSaturation</key>
<real>0.44501984119415283</real>

So, these values are the one I choose last time I started Xcode, but once I opened xcode again, if I go in the preferences, the saturation and brightness will be back to 0.

Looks like my values are well stored, but just not reloaded in Xcode

**Comment by tbaranes** [comment]
In fact, it's always after closing Xcode, not link to shut down the mac

**Comment by kolinkrewinkel** [comment]
What version of Xcode and OS X are you running? In addition, do you see any Console errors? I remember we dealt with something like this before, but it's odd that it'd be able to read the rest of the theme except these keys.

**Comment by tbaranes** [comment]
Oh, I understood my error by reading your answer, I'm using the tool with one of the native theme (dusk). Just try it with one of your theme, working well.

Nevermind, sorry for time lost and thanks for the help~

**Comment by kolinkrewinkel** [comment]
Not a problem, this is still an issue I'd like to resolve. The native themes don't play nice with being modified, but if you still wanna use it, you can duplicate it/move it to the user directory where others are stored and set the brightness/saturation vars.

**Comment by tbaranes** [comment]
In fact, modified them is working perfectly. Just the moment to reset them isn't working, I will do as you say, duplicate them. That's a good idea. Thanks for it!
