### ISSUE TITLE
Not working with Xcode 7.1 beta (7B60)

### ISSUE THREAD

**Issue by ferologics** [kolinkrewinkel/Polychromatic#70]
yea.. I love this plugin, can we do anything about this? Anyone has a solution or is it just me?

**Comment by aure** [comment]
I have this problem and I can't believe how much I miss Polychromatic on 7.1!!!

**Comment by ShingoFukuyama** [comment]
[Fixed for Xcode 7.0.1 El Capitan](https://github.com/ShingoFukuyama/Polychromatic)
Does this also work on 7.1 beta? Currently pull-requesting.

**Comment by aure** [comment]
It doesn't seem to work on 7.1, no.  :(

On Sat, Oct 10, 2015 at 7:04 PM, Shingo Fukuyama <notifications@github.com>
wrote:

> Fixed for Xcode 7.0.1 El Capitan
> <https://github.com/ShingoFukuyama/Polychromatic>
> Does this also work on 7.1 beta? Currently pull-requesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kolinkrewinkel/Polychromatic/issues/70#issuecomment-147145015>
> .
>



-- 
Sent From My iPhone

**Comment by ShingoFukuyama** [comment]
@aure Thank you for trying.
I confirmed it works after adding UUID for Xcode 7.1 beta 3 in info.plist.
Could you try it again?
[Add UUID for Xcode 7.1 beta 3](https://github.com/ShingoFukuyama/Polychromatic)

**Comment by aure** [comment]
Hallelujah it works!

On Sat, Oct 10, 2015 at 9:11 PM, Shingo Fukuyama <notifications@github.com>
wrote:

> @aure <https://github.com/aure> Thank you for trying.
> I confirmed it works after adding UUID for Xcode 7.1 beta 3 in info.plist.
> Could you try it again?
> Add UUID for Xcode 7.1 beta 3
> <https://github.com/ShingoFukuyama/Polychromatic>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kolinkrewinkel/Polychromatic/issues/70#issuecomment-147152593>
> .
>



-- 
Sent From My iPhone

**Comment by kolinkrewinkel** [comment]
Thanks @ShingoFukuyama!

**Comment by Danappelxx** [comment]
Need to add one for the new beta as well.
For my Xcode (7.2 beta 7C46I) it is: `9AFF134A-08DC-4096-8CEE-62A4BB123046`
