### ISSUE TITLE
Xcode 7.2 - Issues with poly themes - colors removed

### ISSUE THREAD

**Issue by jakeatwork** [kolinkrewinkel/Polychromatic#74]
I've tried uninstalling everything (all plugins and themes including alcatraz itself), but when I upgraded to Xcode 7.2, all of the colors disappeared from the installed themes. The themes are still there and can be activated, they are just now monochromatic as seen below:

![image](https://cloud.githubusercontent.com/assets/1273830/11758664/d3c52632-a022-11e5-900c-adca4632e588.png)

Love this plugin...really useful. Let me know if I can help in any way.

**Comment by twof** [comment]
+1

**Comment by kolinkrewinkel** [comment]
If you look in the `Variables` panel, what' it show as the values?

**Comment by jakeatwork** [comment]
![image](https://cloud.githubusercontent.com/assets/1273830/11904546/a8553c14-a575-11e5-8451-c7119e548c1c.png)

**Comment by jakeatwork** [comment]
![image](https://cloud.githubusercontent.com/assets/1273830/11904564/bc42c69c-a575-11e5-90dc-bf813b6d0ca7.png)

**Comment by twof** [comment]
This appears to have been fixed for me.

**Comment by jakeatwork** [comment]
@twof - what did you do?

**Comment by twof** [comment]
@jakeatwork Nothing at all. I just popped open xcode yesterday and everything was working. I think they updated the plugin, so try closing xcode and reopening it maybe. 
<img width="1440" alt="screen shot 2015-12-18 at 9 06 03 pm" src="https://cloud.githubusercontent.com/assets/5561501/11911470/39427fde-a5cb-11e5-9243-4dbb1e330ad6.png">

**Comment by kolinkrewinkel** [comment]
I think the reason this happens is a detail of Alcatraz: I believe on one launch it downloads and copies in new updates for the plugins. On another launch, those are then loaded.

**Comment by jakeatwork** [comment]
woot...got it working again. removed both the plugin and themes, restarted, then reinstalled and they are working now. thanks!
