### ISSUE TITLE
Missing Polychromatic Colour Theme

### ISSUE THREAD

**Issue by micnguyen** [kolinkrewinkel/Polychromatic#75]
On XCode 7.2, with Polychromatic installed via Alcatraz - the colour themes are missing. Attempting to open the plugin in Finder shows that the themes do exist there.

**Comment by kolinkrewinkel** [comment]
Hmm. If you repeat the "Install Sample Themes" process under Editor -> Polychromatic, do they get copied to `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`? It should show a dialog if there's an error, but maybe there's a way it's silently failing....

**Comment by micnguyen** [comment]
Hi. Thanks - I've just done that and now the theme is installed. However, applying the theme - it makes most of the text grey?
